[Main]
# URL of the remote work generation node
NodeRpc = "http://path.to.nanonode:port/apipath/"

# Binding address of the service, ":7176" by default
ListenIpPort = ":7176"

# CacheFile name: if set, this file is used to persist the cache content.
# Should be full or relative path.  If it is empty, persistence to file is not used.
CachePeristFileName = ""

# HTTP API Rate limit: max concurrent outstanding requests.  If reached, overload error messages are returned.
# Background-running work requests are counted in here, they are limited differently
RestMaxActiveRequests = 500

# BackgroundWorkerCount: number of background worker threads, and also maximum number of outgoing requests from pregenerations
# Range: 2 - 20, default 4
BackgroundWorkerCount = 4

# MaxOutRequests: number of concurrent outgoing work request (both from generation and pregeneration).
# Range: 3 - 30, default 8, but must be at least 1 larger than BackgroundWorkerCount
MaxOutRequests = 8

# MaxCacheAgeDays: age limit on old cache entries for cache aging.  0 means no cache aging.
# Dafault: 30 (days)
MaxCacheAgeDays = 30
